export const heroMovies = [
  {
    id: 1013343,
    year: 2023,
    rating: '7.4',
    title: 'Вонка',
    genre: 'Семейный',
    image: '/images/hero-7.jpg',
  },
  {
    id: 4664634,
    year: 2023,
    rating: '8.3',
    title: 'Оппенгеймер',
    genre: 'История',
    image: '/images/hero-1.jpg',
  },
  {
    id: 478052,
    year: 2023,
    rating: '6.6',
    title: 'Барби',
    genre: 'Фэнтези',
    image: '/images/hero-2.jpg',
  },
  {
    id: 4511543,
    year: 2023,
    rating: '6.7',
    title: 'Оставь мир позади',
    genre: 'Фантастика',
    image: '/images/hero-3.jpg',
  },
  {
    id: 1044002,
    year: 2023,
    rating: '7.6',
    title: 'Гран туризмо',
    genre: 'Спорт',
    image: '/images/hero-4.jpg',
  },
  {
    id: 1437923,
    year: 2023,
    rating: '6.5',
    title: 'Наполеон',
    genre: 'История',
    image: '/images/hero-5.jpg',
  },
  {
    id: 4499408,
    year: 2023,
    rating: '6.5',
    title: 'Создатель',
    genre: 'Драма',
    image: '/images/hero-6.jpg',
  },
];
